---
- name: Testing andrewrothstein.serf
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'serf --version'
      ansible.builtin.command: serf --version
      changed_when: false
      register: serf_test_output
    - name: Output of 'serf --version'
      ansible.builtin.debug:
        msg: '{{ serf_test_output.stdout }}'
