---
- name: Installing consul binaries
  ansible.builtin.include_role:
    name: andrewrothstein.hashi
  vars:
    hashi_apps:
      - name: '{{ serf_app.name | default("serf") }}'
        ver: '{{ serf_app.ver | default(serf_ver) }}'
        meta: '{{ serf_app.meta | default("") }}'
